<?php
require_once 'inc/server.php';
$reportQuery = select('*', 'tit_courses,tit_teacher,tit_teachcourse,tit_student,course_stu', "tit_courses.cou_id=tit_teachcourse.cou_id AND tit_teacher.tea_code=tit_teachcourse.tea_code AND course_stu.cou_id=tit_courses.cou_id AND tit_student.st_id=course_stu.st_id AND tit_teachcourse.cou_id=course_stu.cou_id");
foreach ($reportQuery as $reportRow) {
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <title>T-IT software : All courses reports</title>
    <!-- Web Fonts
======================= -->
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900' type='text/css'>
    <!-- Stylesheet
======================= -->
    <link rel="stylesheet" type="text/css" href="../../assets/printer/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="../../assets/printer/css/all.css" />
    <link rel="stylesheet" type="text/css" href="../../assets/printer/css/tit-print.css" />

</head>

<body style="background-color: #fff !important;">
    <!-- Container -->
    <div class="container-fluid invoice-container" style="max-width: 970px !important;">
        <!-- Header -->
        <header>
            <div class="row align-items-center">
                <div class="col-sm-7 text-center text-sm-left mb-3 mb-sm-0"> <img id="logo" src="../../assets/dashboard/img/logo/Online_Business_School_Logo.jpg" style="width: 180px;" title="Koice" alt="Koice" /> </div>
                <div class="col-sm-5 text-center text-sm-right">
                    <h4 class="mb-0">T-IT Africa School</h4>
                    <p class="mb-0">Report N<sup>0</sup> <?php echo 'RE' . codeGenerator(); ?></p>
                </div>
            </div>
            <hr>
        </header>

        <!-- Main Content -->
        <main>
            <div class="row">

                <div class="col-sm-6 order-sm-0"> <strong>MINISTRY OF EDUCATION</strong>
                    <address>
                        GASABO DISTRICT<br />
                        KACYIRU SECTOR<br />
                        <?php echo $dateSt; ?>
                    </address>
                </div>
            </div>

            <br>
            <h4 class="text-center">Report of students with their courses </h4>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th class="text-left"><strong>Courses names</strong></th>
                            <th class="text-left"><strong>Courses Code</strong></th>
                            <th class="text-left"><strong>Teacher names</strong></th>
                            <th class="text-left"><strong>Students list</strong></th>

                        </tr>
                    </thead>
                    <tbody>
                        <?php $courses = select('*', 'tit_courses,tit_teachcourse,tit_teacher', "tit_courses.cou_id=tit_teachcourse.cou_id AND tit_teacher.tea_code=tit_teachcourse.tea_code"); ?>

                        <tr>
                            <?php foreach ($courses as $courseRow) {
                                $courseId = $courseRow['cou_id'];
                            ?>

                                <td class="text-left"><?php echo $courseRow['cou_title']; ?></td>
                                <td class="text-left"><?php echo $courseRow['cou_code']; ?></td>
                                <td class="text-left"><?php echo $courseRow['tea_names']; ?></td>
                                <td class="text-left">
                                <?php
                                $studentSelector = select('*', 'tit_student,course_stu', "tit_student.st_id=course_stu.st_id AND course_stu.cou_id='$courseId' and course_stu.stuco_status='1'");
                                foreach ($studentSelector as $rowStudent) {

                                ?>

                                    <?php echo $rowStudent['st_fullnames']; ?> <br>
                                <?php } ?>
                                </td>

                        </tr>
                    <?php } ?>

                    </tbody>
                </table>
            </div>
        </main>
        <!-- Footer -->
        <footer class="text-right">
            <p class="text-1">Generated by T-IT school software</p>
            <div class="btn-group btn-group-sm d-print-none"> <a href="javascript:window.print()" class="btn btn-success border text-light-50 shadow-none"> Print Document</a> </div>
        </footer>
    </div>
    <!-- Back to My Account Link -->
</body>

</html>