<?php
require_once 'inc/server.php';
@$decrypt = decryptId($_GET['requestCourse']);
@$reportQuery = select('*', 'tit_courses,tit_teacher,tit_teachcourse,tit_student,course_stu', "tit_courses.cou_id=tit_teachcourse.cou_id AND tit_teacher.tea_code=tit_teachcourse.tea_code AND course_stu.cou_id=tit_courses.cou_id AND tit_student.st_id=course_stu.st_id AND tit_teachcourse.cou_id=course_stu.cou_id AND tit_courses.cou_id='$decrypt'");
if (!$reportQuery) {
    header("location:./");
}
foreach ($reportQuery as $reportRow) {
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <title>T-IT software : courses reports</title>
    <!-- Web Fonts
======================= -->
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900' type='text/css'>
    <!-- Stylesheet
======================= -->
    <link rel="stylesheet" type="text/css" href="../../assets/printer/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="../../assets/printer/css/all.css" />
    <link rel="stylesheet" type="text/css" href="../../assets/printer/css/tit-print.css" />

</head>

<body style="background-color: #fff !important;">
    <!-- Container -->
    <div class="container-fluid invoice-container" style="max-width: 920px !important;">
        <!-- Header -->
        <header>
            <div class="row align-items-center">
                <div class="col-sm-7 text-center text-sm-left mb-3 mb-sm-0"> <img id="logo" src="../../assets/dashboard/img/logo/Online_Business_School_Logo.jpg" style="width: 180px;" title="Koice" alt="Koice" /> </div>
                <div class="col-sm-5 text-center text-sm-right">
                    <h4 class="mb-0">T-IT School</h4>
                    <p class="mb-0">Report N<sup>0</sup> <?php echo 'RE' . codeGenerator(); ?></p>
                </div>
            </div>
            <hr>
        </header>

        <!-- Main Content -->
        <main>
            <div class="row">

                <div class="col-sm-6 order-sm-0"> <strong>MINISTRY OF EDUCATION</strong>
                    <address>
                        GASABO DISTRICT<br />
                        KACYIRU SECTOR<br />
                        <?php echo $dateSt; ?>
                    </address>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 mb-3"> <strong><?php echo $reportRow['cou_title']; ?></strong><br>
                    <span><?php echo $reportRow['cou_code']; ?></span>
                </div>
                <div class="col-sm-6 mb-3 text-sm-right"> <strong><?php echo $reportRow['tea_names']; ?></strong><br>
                    <span><?php echo $reportRow['tea_email']; ?></span>
                </div>
            </div>
            <br>
            <h4 class="text-center">List of students learning <?php echo $reportRow['cou_title']; ?> </h4>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <td class="text-center"><strong>Student names</strong></td>
                            <td class="text-center"><strong>Student email</strong></td>
                            <td class="text-center"><strong>Date of birth</strong></td>
                            <td class="text-center"><strong>Gender</strong></td>
                            <td class="text-center"><strong>Address</strong></td>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $reportQuery1 = select('*', 'tit_courses,tit_teacher,tit_teachcourse,tit_student,course_stu,tit_gender', "tit_courses.cou_id=tit_teachcourse.cou_id AND tit_teacher.tea_code=tit_teachcourse.tea_code AND course_stu.cou_id=tit_courses.cou_id AND tit_student.st_id=course_stu.st_id AND tit_teachcourse.cou_id=course_stu.cou_id AND tit_student.ge_id=tit_gender.ge_id AND tit_courses.cou_id='$decrypt'");
                        foreach ($reportQuery1 as $reportRow1) {
                        ?>
                        <tr>
                            <td class="text-center"><?php echo $reportRow1['st_fullnames']; ?></td>
                            <td class="text-center"><?php echo $reportRow1['st_email']; ?></td>
                            <td class="text-center"><?php echo $reportRow1['st_dob']; ?></td>
                            <td class="text-center"><?php echo $reportRow1['ge_name']; ?></td>
                            <td class="text-center"><?php echo $reportRow1['st_address']; ?></td>
 
                        </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </main>
        <!-- Footer -->
        <footer class="text-right">
            <p class="text-1">Generated by T-IT school software</p>
            <div class="btn-group btn-group-sm d-print-none"> <a href="javascript:window.print()" class="btn btn-success border text-light-50 shadow-none"> Print Document</a> </div>
        </footer>
    </div>
    <!-- Back to My Account Link -->
</body>

</html>